=== jandias/projeto-obras-1213/obras-1213-web/obras-1213/Content/xml/comunicados.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:myns="si2.isel.pt/2013/TrabFinal" targetNamespace="si2.isel.pt/2013/TrabFinal"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

  <xs:element name="comunicados">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="oficina" minOccurs="0" maxOccurs="unbounded" >
          <xs:complexType>
            <xs:sequence>
              <xs:element name="departamento" type="myns:departamentoType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="codOfic" type="xs:integer"/>
          </xs:complexType>
          <xs:key name="departamentoKey">
            <xs:selector xpath="myns:departamento"/>
            <xs:field xpath="@codDep"/>
          </xs:key>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:key name="oficinaKey">
      <xs:selector xpath="myns:oficina"/>
      <xs:field xpath="@codOfic"/>
    </xs:key>
    <xs:key name="comunicadoKey">
      <xs:selector xpath="myns:oficina/myns:departamento/myns:comunicado"/>
      <xs:field xpath="@idCom"/>
    </xs:key>

  </xs:element>

  <xs:complexType name="departamentoType">
    <xs:sequence>
      <xs:element name="comunicado" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="tipo" type="myns:tipoType" minOccurs="1" maxOccurs="1" />
            <xs:element name="autor" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="data" type="myns:dataType" minOccurs="1" maxOccurs="1"/>
            <xs:choice>
              <xs:sequence>
                <xs:element name="conteudo" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="urlPrint" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
                <xs:element name="urlMedia" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
              </xs:sequence>
              <xs:sequence>
                <xs:element name="urlPrint" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
                <xs:element name="urlMedia" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
              </xs:sequence>
              <xs:sequence>
                <xs:element name="urlMedia" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
              </xs:sequence>
            </xs:choice>
          </xs:sequence>
          <xs:attribute name="idCom" type="xs:integer"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="codDep" type="xs:integer"/>
  </xs:complexType>

  <xs:complexType name="dataType">
    <xs:simpleContent>
      <xs:extension base="xs:date">
        <xs:attribute name="entrada-em-vigor" type="xs:date" default="2014-01-10" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="tipoType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="aviso"/>
      <xs:enumeration value="informação"/>
      <xs:enumeration value="legislação"/>
      <xs:enumeration value="anúncio"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== jandias/projeto-obras-1213/SQL/comunicados/comunicados.xml
<?xml version="1.0"?>
<myns:comunicados xmlns:myns="si2.isel.pt/2013/TrabFinal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="si2.isel.pt/2013/TrabFinal file:///C:/Users/w/Desktop/PC/testes/PC_1112i/Teste1Ep/Synchronizers/comunicados.xsd">
  <myns:oficina codOfic="1">
    <myns:departamento codDep="1">
      <myns:comunicado idCom="1">
        <myns:autor>Joel Santos</myns:autor>
        <myns:tipo>anúncio</myns:tipo>
        <myns:data entrada-em-vigor="2013-12-01">2013-02-01</myns:data>
        <myns:conteudo>Conforme solicitado pela administração, vimos por este meio comunicar um comunicado. Saudações corporativas.</myns:conteudo>
      </myns:comunicado>
      <myns:comunicado idCom="2">
        <myns:tipo>informação</myns:tipo>
        <myns:autor>Joel Santos</myns:autor>
        <myns:data>2013-01-02</myns:data>
        <myns:conteudo>A partir do presente dia deixaremos de contar com o funcionário número 29007, dispensado compulsivamente.</myns:conteudo>
      </myns:comunicado>
    </myns:departamento>
    <myns:departamento codDep="2">
      <myns:comunicado idCom="1">
        <myns:tipo>anúncio</myns:tipo>
        <myns:autor>Maria Silvina</myns:autor>
        <myns:data>2012-12-20</myns:data>
        <myns:conteudo>Bom natal para todos os colegas.</myns:conteudo>
      </myns:comunicado>
    </myns:departamento>
  </myns:oficina>
  <myns:oficina codOfic="2">
    <myns:departamento codDep="1">
      <myns:comunicado idCom="1">
        <myns:tipo>legislação</myns:tipo>
        <myns:autor>Manuel dos Santos</myns:autor>
        <myns:data>2012-11-20</myns:data>
        <myns:conteudo>Carissimos, serve o presente para informar que a adesão à greve é obrigatória.</myns:conteudo>
      </myns:comunicado>
    </myns:departamento>
  </myns:oficina>
</myns:comunicados>
